### 📌 Criar novo documento
POST http://localhost:8080/document/register
Content-Type: application/json

{
  "type": "CPF",
  "issueDate": "2010-05-20",
  "number": "12345678900"
}

### 📌 Listar todos os documentos
GET http://localhost:8080/documents

### 📌 Buscar documento por ID
GET http://localhost:8080/document/1

### 📌 Atualizar documento
PUT http://localhost:8080/document/update
Content-Type: application/json

{
  "id": 1,
  "type": "RG",
  "issueDate": "2015-08-10",
  "number": "987654321"
}

### 📌 Deletar documento
DELETE http://localhost:8080/document/delete
Content-Type: application/json

{
  "id": 1
}
